baseURL = 'https://pal-ku.github.io/'
languageCode = 'en-us'
title = 'PAL-KU'
theme = 'blowfish'

[params]
  colorScheme = "slate"
  logo = "img/logo.png"
  disableTextInHeader = true
  highlightCurrentMenuArea = true
  defaultAppearance = "light" 
  autoSwitchAppearance = false
  enableThemeToggle = false
  mainSections = ["news", "publications", "research"] 
  
  # Homepage configuration
  [params.homepage]
    layout = "profile"
    showRecent = true
    showRecentItems = 5

  [params.header]
    layout = "fixed-fill-blur"

  [params.list]
    layoutBackgroundBlur = false
    layoutBackgroundHeaderSpace = false

  [params.footer]
    showAppearanceSwitcher = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 20
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 30
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 40
  [[menu.main]]
    name = "People"
    url = "/people/"
    weight = 50
  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 60

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Needed for custom HTML in partials if used
