baseURL = 'https://pal-ku.github.io/'
languageCode = 'en-us'
title = 'PAL'
theme = 'blowfish'

[params]
  colorScheme = "slate"
  logo = "img/logo.png"
  disableTextInHeader = true
  highlightCurrentMenuArea = true
  defaultAppearance = "light" 
  autoSwitchAppearance = false
  enableThemeToggle = false
  mainSections = ["news", "publications", "research"] 

  [params.author]
    name = "Photonic Architecture Laboratories"
    headline = ""
    image = "img/logo.png"
  
  # Homepage configuration
  [params.homepage]
    layout = "background"
    homepageImage = "img/homepage/hero.png"
    layoutBackgroundBlur = true
    showRecent = true
    showRecentItems = 5
    cardView = true
    cardViewScreenWidth = true

  [params.header]
    layout = "fixed-fill-blur"

  [params.list]
    layoutBackgroundBlur = true
    layoutBackgroundHeaderSpace = false
    cardView = true
    cardViewScreenWidth = false
    showCards = true
    showSummary = true

  [params.footer]
    showAppearanceSwitcher = false
    showPoweredBy = false
    showThemeAttribution = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 20
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 30
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 40
  [[menu.main]]
    name = "People"
    url = "/people/"
    weight = 50
  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 60

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Needed for custom HTML in partials if used
